id: P004439
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W21619
  title: བྱང་ཆུབ་གཞུང་ལམ་དང་རྩ་ལྟུང་རྣམ་བཤད
  author: ''
  volumes:
    522dff4f6139408fb216b3f09400434b:
      image_group_id: I5799
      title: ''
      volume_number: 1
      total_pages: 422
      base_file: v001.txt
